### PR TITLE
updated deprecated alerts issues for ios9

### PR DESCRIPTION
**Pull request by ptclou**

### CODE REVIEW

**Comment by johnCbogil** [comment]
Hey @ptcloutier great start. There's still a little more work to do. When I ran the app there appears to still be 3 deprecation warnings. Maybe you did the work and forgot to commit or maybe you missed them nbd. 

There's also a merge conflict. Here's an overly-simplified explanation: Merge conflicts occur when for example, you're trying to merge two branches and the branches have different code at the same line number. Like if branch A has "[self foo]" at line 43, but branch B has "[self bar]" at line 43. Git doesn't know how to merge those, its not sure which one is correct, so you have to tell it manually. 

Anyways the person creating the PR is supposed to address this by **first** merging develop into 185-ios9, and **then** creating a pr to merge 185-ios9 into develop. Its kind of like a courtesy to the person who maintains the repo but it's more than just a courtesy. Normally I would just address the conflict myself bc this case is relatively simple but its a good chance for you to learn and we're in no rush. I don't know how to address merge conflicts in terminal, so feel free to take a stab at it. If you can't figure it out I don't blame you at all, feel free to wait until Monday and ask Oren or someone. Lmk how it goes!

**Comment by ptclou** [comment]
Hey John, this is ready for your review. Thank you! ~Perrin

**Comment by ptclou** [comment]
Thanks for the feedback! Found the outstanding warnings, fixed and pushed them. I didn't see those warnings at first even after I built and ran it a few times ( I actually had to do a search for the deprecated 'UIAlertView' and once I visited the .m where they lived I was hit with the 3 warnings I was looking for. Weird they didn't pop up before, not sure why they wouldn't show at build time. Thanks again for your help and it's already been a great learning experience for me, quite enjoyable. 
Will work on the pr tomorrow, the right way this time.

**Comment by ptclou** [comment]
Thanks John, you're explanation was really helpful, sorry about my 'git ignor'ance, will get right back to it!

**Comment by ptclou** [comment]
I'm gonna need  to get a little git guidance, have to wait til Monday
morning like you suggested.

On Sat, Oct 22, 2016 at 12:17 AM, Perrin Cloutier <cloutier.perrin@gmail.com

> wrote:
> 
> Thanks for the feedback! Found the outstanding warnings, fixed and pushed
> them. I didn't see those warnings at first even after I built and ran it a
> few times ( I actually had to do a search for the deprecated 'UIAlertView'
> and once I visited the .m where they lived I was hit with the 3 warnings I
> was looking for. Weird they didn't pop up before, not sure why they
> wouldn't show at build time. Thanks again for your help and it's already
> been a great learning experience for me, quite enjoyable.
> Will work on the pr tomorrow, the right way this time.
>

**Pull request merged**
