### PR TITLE
Add group zero state

### PR DESCRIPTION
**Pull request by dknomura**

### CODE REVIEW

**Comment by johnCbogil** [comment]
Hey @dknomura, we don't want to use a tableViewCell as the zerostate. It opens up more edge cases, that are solvable, but we don't want to deal with. For example, if I try to delete your zerostate tableviewcell, the app crashes. Of course we can add a check to prevent that, but we don't want to litter our code with if/else statements. 

Instead what I would recommend is this: http://stackoverflow.com/questions/15746745/handling-an-empty-uitableview-print-a-friendly-message .

Thanks and lmk how it goes

**Comment by dknomura** [comment]
Ok I added the zero state to the background view.

**Comment by johnCbogil** [comment]
@dknomura awesome thank you. Can you also add a zerostate for when the actions page is selected? (there was a different issue for this but I closed it and edited this issue). Thanks

**Comment by dknomura** [comment]
done

**Comment by johnCbogil** [comment]
@dknomura Thanks man. I merged it to master and will be deleting the branch. Lmk if you wanna pick up another ticket

**Pull request merged**
