### PR TITLE
372 reps contact forms

### PR DESCRIPTION
**Pull request by ptclou**
AppDelegate calls on RepsManager to get contact forms, RepsManager calls NetworkManager to make network request. Completion blocks only in the NetworkManager method. If success, RepsManager sets a dictionary property with all the contact forms. The contact form is actually accessed when RepsManager calls 'createFederalRepresentativesFromLocation:' and is set in the results dictionary used to init the FederalRepresentative using the bioguide.
There are checks for nil in RepsManager getContactFormWithBioguide: and in FederalRepresentative getContactFormURL:(NSString *)urlString.

### CODE REVIEW

**Comment by johnCbogil** [comment]
Hey @ptcloutier this isn't building for me, did you test it? Perhaps it's something on my end?

**Comment by ptclou** [comment]
There was another place where the old json file was being accessed, not
sure how I missed this since I had tested it before and wasn't an issue, no
problem, patching it up right now.

**Comment by ptclou** [comment]
The actiondetailvc was accessing the old json file, I changed the method to access the email from the rep's new contactformurl property.

**Comment by ptclou** [comment]
Also fixed a couple things in the webview it was presenting. There was a distracting horizontal scroll indicator(hid it) and the back button on the nav bar is hidden now. To do this you must set the title to the nav bar button to an empty string in the vc that is presenting the next vc.

**Comment by johnCbogil** [comment]
Hey i created a bug previously that was preventing ALL reps except feds from having emails. Sorry! This is good now thanks!

**Pull request closed without merging**
